# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95842845fbeba7129d1fe08e00a67685bb51dd1c7fcb10858dd30a829529a3ef6388101a71438d5ad4da801192083d5c0ec87cead502bc4db8013ce7852c39f7

test:
  secret_key_base: b9b899f5eb2f3dfdaf771caa66cdebbca6bda870e62538a2638ebca340c922a9c251d13da41a193a82727d3941eb08022c3b307759c9bd48c97ae45ceb34bb39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
